.github/workflows/ci.yml
=> Add deploy job to deploy to GitHub Pages

src/pages/index.astro
見た目を若干整えました。定例でフィードバックをもらう予定です。
=> イベント名によるアイキャッチを追加

renovate.json
ref. https://docs.renovatebot.com/key-concepts/automerge/#automerge-non-major-updates
=> renovate: automergeを有効にする

.github/workflows/preview.yml, astro.config.mjs, package.json, pnpm-lock.yaml
Fix https://github.com/GoWorkshopConference/2025/pull/36#issuecomment-2629393583
=> Fix preview page base url

README.md
#40 でpnpmのバージョンをv9からv10に更新したので、READMEにも反映する。
=> pnpmのバージョンアップをREADMEに反映

src/pages/index.astro
=> イベントの説明文を掲載

package.json, pnpm-lock.yaml, src/utils/withBase.ts, tsconfig.json, vitest.config.ts
期待する動作をテストコードとして書き出しておきます。
withBase周りは今後それほど変更することはないと思うので、ひとまずはCIでのテスト実行はしないでおきます。
=> withBaseのユニットテストを追加する

src/data/staff/yebis0942.json
=> スタッフ一覧にyebis0942を追加

src/data/staff/kurichi.json
=> スタッフデータの追加（くりち）

src/data/staff/Shuma.json
=> プロフィールお願いいたします。

src/data/staff/makotoyasuda.json
=> プロフィール登録：yasuda

src/data/staff/UserMiyam.json
https://github.com/GoWorkshopConference/2025/issues/179#issuecomment-2959268661 の追加依頼に対応します。
=> Add data/staff/UserMiyam.json

src/data/staff/tesao.json
=> スタッフ追加：てさお

src/data/staff/yuita.json
以下を元に作成しました。
ご確認よろしくお願いします🙇
https://github.com/GoWorkshopConference/2025/issues/179
=> feat: スタッフデータ追加(yuita)

src/data/staff/mas.json
=> mas staff add

src/pages/staff.astro
全員の掲載完了を待たずに公開する見込みなので、注意書きを追加します。
=> スタッフ一覧に「スタッフ一覧は順次更新中です」の注意書きを追加

src/data/staff/kudo.json
スタッフのjsonファイルを追加しました。
確認よろしくお願いします！
=> スタッフ一覧追加: Kudo

src/data/staff/repunit.json
=> feature: add staff data (repunit)

src/data/staff/taramanji.json
#179 
スタッフのJSONを作成しました．ご確認のほどよろしくお願いします．
=> feat:add-staff-json-taramanji

src/data/staff/uji.json
https://github.com/GoWorkshopConference/2025/issues/179
遅くなりましたがスタッフのjsonファイルを追加しました :pray: (プレビュー確認済み)
=> スタッフ一覧追加: uji

src/pages/index.astro
connpassページが公開されたのでWebサイトにも掲載します。
=> connpassの参加申し込みリンクを公開

src/pages/index.astro
=> ワークショップ開催応募のリンクを追加する
